import genToken from "../config/token.js";
import User from "../model/userModel.js";
import bcrypt from "bcryptjs";
import validator from "validator";
import sendMail from "../config/sendMail.js";

export const signUp = async (req, res) => {
    try {
        const {name, email, password, role} = req.body;

        let existUser = await User.findOne({email}); // findOne is used to find the email in db

        if(existUser) {
            return res.status(400).json({ message: "Email already exists" });
        }

        if(!validator.isEmail(email)) {
            return res.status(400).json({ message: "Invalid Email" }); // isEmail is a function in validator which validate the email (email valid h ya nhi)
        }

        if(password.length < 6) {
            return res.status(400).json({ message: "Password must be at least 6 characters long" });
        }

        let hashPassword = await bcrypt.hash(password, 10); // hash is a function in bcryptjs which hash the password

        const user = await User.create({
            name,
            email,
            password: hashPassword,
            role,
            provider: "local" // --------
        });

        /* user create ho chuka hai ab hum token generate karenge (with the help of userId) , aur ye token cookies ke andar
           store ho jayega , to jab hum doobara login karenge to hum login hi milenge */
        // config folder ke andar ye hum karenge -> config/token.js
        
        let token = await genToken(user._id); // user._id is the unique id of the user which is generated by mongodb

        // cookie is a object with has many things
        res.cookie("token", token, { // name of cookie is : token
            httpOnly: true,
            maxAge: 7 * 24 * 60 * 60 * 1000, // 10 days (milliseconds)
            sameSite: "none",
            secure: true // true hoga jab https use karenge
        });
        console.log("✅ Generated Token:", token, "Cookie should be set in browser");

        return res.status(201).json(user);

    } catch(error) {
        console.error("Error occurred during signup:", error);
        return res.status(500).json({ message: "Internal server error" });
    }
};

export const login = async (req, res) => {
    try {
        const {email, password} = req.body;

        let user = await User.findOne({email}); // findOne is used to find the email in db

        // check wheather user(email) exits in db or not
        if(!user) {
            return res.status(400).json({ message: "Email doesn't exists" });
        }

        // 2. If user signed up with Google, block normal login
        if (user.provider === "google") { // -------
        return res.status(400).json({ 
            message: "This account is linked with Google. Please login using Google Sign-in." 
        });
        }

        // match the password 
        let isMatch = await bcrypt.compare(password, user.password); // compare is a function in bcryptjs which compare the password
        // hashedPassword(user.password) user ke andar hoga 

        if(!isMatch) {
            return res.status(400).json({ message: "Incorrect Password" });
        }

        // token isme bhi generate hoga , jaise hi new user login hoga
        
        let token = await genToken(user._id); // user._id is the unique id of the user which is generated by mongodb

        // cookie is a object with has many things
        res.cookie("token", token, { // name of cookie is : token
            httpOnly: true,
            maxAge: 7 * 24 * 60 * 60 * 1000, // 10 days (milliseconds)
            sameSite: "none",
            secure: true
        });
        console.log("✅ Generated Token:", token, "Cookie should be set in browser");
        return res.status(200).json(user); // 200 isliye likha hai because ya pe kuch create nhi ho rha h

    } catch(error) {
        console.error("Error occurred during login:", error);
        return res.status(500).json({ message: "Internal server error" });
    }
};

// logout tab hoga jab jo token cookie se hat jayega

export const logOut = async (req, res) => {
    try {
        await res.clearCookie("token"); // cookie ko clear kar do (token : name of the cookie)
        return res.status(200).json({ message: "Logged out successfully" });
    } catch (error) {
        console.error("Error occurred during logout:", error);
        return res.status(500).json({ message: "Logout error" });
    }
};

// ab hum in sabke routes banayenge : routes/auth.routes.js ke andar


export const sendOTP = async (req, res) => {
    try {
        const {email} = req.body;
        const user = await User.findOne({email})
        if(!user) {
            return res.status(404).json({message: "User not found"})
        }

        const otp = Math.floor(1000 + Math.random() * 9000).toString()

        user.resetOtp = otp,
        user.otpExpires = Date.now() + 5 * 60 * 1000 // 5 minutes
        user.isOtpVerified = false

        await user.save()
        await sendMail(email, otp)
        return res.status(200).json({message:"OTP send successfully"})
    } catch(error) {
        return res.status(500).json({message:`send otp error ${error}`})
    }
}

export const verifyOTP = async (req, res) => {
    try {
        const {email, otp} = req.body;
        const user = await User.findOne({email})
        if(!user || user.resetOtp != otp || user.otpExpires < Date.now()) {
            return res.status(404).json({message: "Invalid OTP"})
        }

        user.isOtpVerified = true,
        user.resetOtp = undefined,
        user.otpExpires = undefined 

        await user.save();

        return res.status(200).json({message:"OTP Verified Successfully"})

    } catch(error) {
        return res.status(500).json({message:`verify otp error ${error}`})
    }
}

export const resetPassword = async (req, res) => {
    try {
        const {email, password} = req.body;
        const user = await User.findOne({email})
        if(!user || !user.isOtpVerified) {
            return res.status(404).json({message: "OTP verification is required"})
        }

        const hashPassword = await bcrypt.hash(password, 10)
        user.password = hashPassword,
        user.isOtpVerified = false

        await user.save()

        return res.status(200).json({message:"Reset Password Successfully"})


    } catch(error) {
        return res.status(500).json({message:`reset password error ${error}`})
    }
}

export const googleAuth = async(req, res) => {
    try {
        const {name, email, role} = req.body
        const user = await User.findOne({email})
        if(!user) { // user is not in db then create a new user
            // If user doesn't exist, check if role is provided (signup)
            if (!role) { // ------
                return res.status(400).json({
                message: "User not found. Please signup first."
                });
            }

            // Create new Google user (signup)
            user = await User.create({
                name, 
                email,
                role,
                password: null,       // explicitly null
                provider: "google" // -------
            }) 
        }
        let token = await genToken(user._id); // user._id is the unique id of the user which is generated by mongodb

        // cookie is a object with has many things
        res.cookie("token", token, { // name of cookie is : token
            httpOnly: true,
            maxAge: 7 * 24 * 60 * 60 * 1000, // 10 days (milliseconds)
            sameSite: "none",
            secure: true
        });
        return res.status(200).json(user); // 200 isliye likha hai because ya pe kuch create nhi ho rha h
    } catch(error) {
        return res.status(500).json({message:`GoogleAuth Error ${error}`})
    }
}
